#!/usr/bin/env python3
"""Generate src/core/include/core/trig_tables.hpp.

Tangent: round(32*y/x) with the fold T[y][x] = 64 - T[x][y] for x < y.
Sine:    round(32767 * sin(2π i / 256)).

Committed as source so a clean clone does not need Python to be correct.
See doc/implementation/A2-determinism-primitives.md section 2.3.
"""
from __future__ import annotations

import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "core" / "include" / "core" / "trig_tables.hpp"


def tangent_table() -> list[list[int]]:
    t = [[0] * 32 for _ in range(32)]
    t[0][0] = -1
    for x in range(1, 32):
        t[0][x] = 0
        t[x][0] = 64
    for y in range(1, 32):
        for x in range(1, 32):
            if x >= y:
                # round(32*y/x) via integer: (64*y + x) // (2*x)
                t[y][x] = (64 * y + x) // (2 * x)
            else:
                t[y][x] = 64 - t[x][y]
    return t


def sine_table() -> list[int]:
    out = []
    for i in range(256):
        v = round(32767.0 * math.sin(2.0 * math.pi * i / 256.0))
        out.append(int(v))
    return out


def main() -> None:
    tan = tangent_table()
    sine = sine_table()

    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("// GENERATED by tools/gen_trig.py — do not edit by hand.")
    lines.append("// See doc/implementation/A2-determinism-primitives.md section 2.3.")
    lines.append("")
    lines.append("namespace at {")
    lines.append("")
    lines.append("// kAngleTangent[dy][dx]: round(32*y/x) in the first quadrant,")
    lines.append("// folded so T[y][x] = 64 - T[x][y] when x < y. Origin is -1.")
    lines.append("inline constexpr std::array<std::array<int8_t, 32>, 32> kAngleTangent = {{")
    for row in tan:
        lines.append("    {" + ", ".join(f"{v:3d}" for v in row) + "},")
    lines.append("}};")
    lines.append("")
    lines.append("// kSineCosineTable[i] ~= round(32767 * sin(2π i / 256)).")
    lines.append("// Consumed as (v >> 8) * speed; the >>8 lane matches the reference")
    lines.append("// table for every entry even where ±1 transcription drift exists.")
    lines.append("inline constexpr std::array<int16_t, 256> kSineCosineTable = {{")
    for i in range(0, 256, 8):
        chunk = ", ".join(f"{v:6d}" for v in sine[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("}};")
    lines.append("")
    lines.append("} // namespace at")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
